name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  camera: ^0.10.5+2
  http: ^1.0.0
  http_parser: ^4.0.2
  flutter_tts: ^3.7.0
  cupertino_icons: ^1.0.2
  photo_manager: ^2.6.0
  gallery_saver: ^2.3.2
  photo_view: ^0.14.0
  sqflite:
  
dependency_overrides:
  http: ^0.13.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets :
    - assets/images/logo.png